version: '2'
services:
  db:
    container_name: db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testable_code_workshop
    ports: 
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/
    networks:
      - back-tier
  web:
    container_name: web
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      - back-tier
  pactdb:
    container_name: pactdb
    image: postgres:9.4
    networks:
      - back-tier
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=pactbroker
      - POSTGRES_PASSWORD=supersave
    networks:
      - back-tier
  pactweb:
    container_name: pactweb
    depends_on:
      - pactdb
    image: flowerpot/pact-broker-pg-docker
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://pactbroker:supersave@pactdb/pactbroker
      #- PACT_BROKER_USERNAME=admin
      #- PACT_BROKER_PASSWORD=admin
    networks:
      - back-tier
networks:
  back-tier:
    driver: bridge
