# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    controller_factory:
        class: AppBundle\Factory\Controller
        arguments: [ "@doctrine.orm.entity_manager" ]
    review_controller:
        class: AppBundle\Controller\ReviewController
        factory: "controller_factory:getReviewController"
