# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    review_controller:
        class: AppBundle\Controller\ReviewController
        arguments: [ "@doctrine.orm.entity_manager" ]
